### ISSUE TITLE
Could not execute entrypoint stage 'main'.

### ISSUE THREAD

**Issue by lesxmore** [MykhailoOpryshok/Borukva-Food#14]
I'm using the latest version of this mod in Fabric 1.21.3.
`java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'borukva-food' at 'com.opryshok.BorukvaFood'!
        at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:403) ~[fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:401) ~[fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:63) ~[fabric-loader-0.16.9.jar:?]
        at knot/net.minecraft.server.Main.main(Main.java:111) [server-intermediary.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) [fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.16.9.jar:?]
        at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) [fabric-server-launch.jar:1.0.1]
Caused by: java.lang.NoSuchMethodError: 'eu.pb4.polymer.resourcepack.api.PolymerModelData eu.pb4.polymer.resourcepack.api.PolymerResourcePackUtils.requestModel(net.minecraft.class_1792, net.minecraft.class_2960)'
        at knot/com.opryshok.ui.UiResourceCreator.genericIconRaw(UiResourceCreator.java:68) ~[borukva-food-0.1.6.jar:?]
        at knot/com.opryshok.ui.UiResourceCreator.icon16(UiResourceCreator.java:64) ~[borukva-food-0.1.6.jar:?]
        at knot/com.opryshok.ui.GuiTextures.<clinit>(GuiTextures.java:17) ~[borukva-food-0.1.6.jar:?]
        at knot/com.opryshok.BorukvaFood.onInitialize(BorukvaFood.java:46) ~[borukva-food-0.1.6.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399) ~[fabric-loader-0.16.9.jar:?]
        ... 7 more`

**Comment by Stikulzon** [comment]
You must install last version of the Polymer: https://modrinth.com/mod/polymer
